Generate token lists for nova
OffchainLabs/arb-token-lists pull request #29
Opened 2022-08-03 20:27 UTC by shbhakta

2022-08-15 21:03 UTC, shbhakta commented on src/lib/utils.ts
> +export const isArb1 = yargs.l2NetworkID === 42161;
do we need isArb1 anywhere if we're checking for isNova?

2022-08-17 12:49 UTC, fredlacs requested changes

2022-08-17 12:49 UTC, fredlacs commented on src/lib/token_list_gen.ts
> +        false);
there is a default value of false for this, so we don't need to add to every time we call

2022-08-17 12:49 UTC, fredlacs commented on src/lib/token_list_gen.ts
> +        3,
seems like we use this value everywhere, lets add it as a default value to simplify calling the `promiseErrorMultiplier`

2022-08-17 12:49 UTC, fredlacs commented on src/lib/token_list_gen.ts
> +      let l2GatewayAddressesFromL1Temp = await promiseErrorMultiplier(getL2GatewayAddressesFromL1Token(addrs, l2.multiCaller, l2.network), (error) => getL2GatewayAddressesFromL1Token(addrs, l2.multiC
would be good to break this down into multiple lines (or use prettier formatter to lint it)

2022-08-23 12:51 UTC, fredlacs approved these changes
LGTM

2022-08-23 12:51 UTC, merged