chore: Remove get path
OffchainLabs/arb-token-lists pull request #84
Opened 2023-03-10 07:15 UTC by Jason-Wanxt

2023-03-10 12:12 UTC, chrstph-dvx approved these changes

2023-03-10 15:27 UTC, Jason-Wanxt commented on update_all
Ohhh, you are right, updated that file too, for this file, do we need to remove it? Or we can open a new pr for this one.

2023-03-13 22:54 UTC, DZGoldman commented on src/commands/full.ts
> -import { ETHERSCAN_LIST_NAME } from '../lib/constants';
can we remove ETHERSCAN_LIST_NAME from constants?

2023-03-13 22:55 UTC, DZGoldman commented on src/lib/token_list_gen.ts
> -import { TOKENLIST_DIR_PATH } from './constants';
can we remove TOKENLIST_DIR_PATH from constants?

2023-03-13 22:55 UTC, DZGoldman commented on src/lib/token_list_gen.ts
> -import { getPrevList, listNameToFileName } from './store';
can we remove listNameToFileName from store?

2023-03-13 22:56 UTC, DZGoldman commented on src/lib/store.ts
> -  const path = arbifiedList ?? getPath(l1ListName);
remove `getPath` funciton?

2023-03-13 22:57 UTC, DZGoldman requested changes
looks good - can clean / remove some more vars i think

2023-03-14 11:16 UTC, chrstph-dvx approved these changes

2023-03-14 22:29 UTC, DZGoldman approved these changes

2023-03-15 02:17 UTC, merged